
-----------------------------------------------
-- PROYECCIONES DE TIPO DE CAMBIO
-----------------------------------------------

-- OBTIENE EL TIPO DE CAMBIO DE LA FECHA ESPECIFICADA
CREATE OR REPLACE PROCEDURE SP_OBTENERTC(
  PDATE IN DATE,
  PRESULT OUT NUMBER
) IS
  MES NUMBER(2);
  ANIO NUMBER(4);
BEGIN
  -- OBTENER EL MES Y ANIO DE LA FECHA
  SELECT 
    EXTRACT(MONTH FROM PDATE),EXTRACT(YEAR FROM PDATE) INTO MES,ANIO
  FROM DUAL;
  -- SELECCIONE EL TIPO DE CAMBIO DE LA TABLA DE TIPOS DE CAMBIO
  SELECT
    TC.MONTO INTO PRESULT
  FROM T_TIPOCAMBIOS TC
  WHERE TC.MES = MES AND TC.ANIO = ANIO;
END;


-- PROYECTA EL TIPO DE CAMBIO PARA EL SIGUIENTE MES DE LA FECHA ESPECIFICADA
CREATE OR REPLACE PROCEDURE SP_PROYECCIONTC1MES(
    PNUMVALREALES IN NUMBER,
    PDATE IN DATE,
    -- PARA INSERT SOLAMENTE
    PCODMONEDA1 IN NUMBER,
    PCODMONEDA2 IN NUMBER,
    PCODIDECONO IN VARCHAR2,
    PNEXTTC OUT NUMBER
) IS
  MES NUMBER(2);
  ANIO NUMBER(4);
  CURTC NUMBER(17,2);     -- VALOR DEL TC DE LA FECHA
  TC0 NUMBER(17,2);       -- VARIABLE DE CONTROL DE MONTO DE TIPO DE CAMBIO (MININUENDO)
  TC1 NUMBER(17,2);       -- VARIABLE DE CONTROL DE MONTO DE TIPO DE CAMBIO (SUSTRAENDO)
  DIFF NUMBER(17,2);      -- VARIABLE DE CONTROL DE MONTO (DIFERENCIA ENTRE MONTOS DE 2 MESES CONSECUTIVOS)
  NEWFECHA DATE;          -- NUEVA FECHA DE DONDE OBTENER EL MONTO DEL TIPO DE CAMBIO
  CONTA NUMBER(10);       -- CONTROL DEL BUCLE
BEGIN
  -- INICIALIZA VARIABLES
  -- OBTENER EL TIPO DE CAMBIO DEL MES ACTUAL
  SP_OBTENERTC(SYSDATE, CURTC);
  TC0 := 0.0;
  TC1 := 0.0;
  CONTA := 0;
  DIFF := 0.0;
  -- BUCLE DE RECORRIDO EN LA TABLA TC SEGUN EL NUMERO DE VALORES REALES
  WHILE (CONTA < PNUMVALREALES)
  LOOP
    -- OBTIENE EL TIPO DE CAMBIO DEL MES ACTUAL
    SELECT 
      ADD_MONTHS(sysdate,- CONTA) INTO NEWFECHA 
    FROM DUAL;
    SP_OBTENERTC(NEWFECHA,TC0);
    -- OBTIENE EL TIPO DE CAMBIO DEL MES ANTERIOR
    SELECT 
      ADD_MONTHS(sysdate,- (CONTA+1)) INTO NEWFECHA 
    FROM DUAL;
    SP_OBTENERTC(NEWFECHA,TC1);
    -- CALCULA DIFERENCIAS
    DIFF := DIFF + (TC0 - TC1);
    CONTA := CONTA + 1;
  END LOOP;
  -- CALCULA EL PROMEDIO
  DIFF := (DIFF / PNUMVALREALES);
  -- CALCULA EL TIPO DE CAMBIO PARA EL SIGUIENTE MES
  CURTC := (CURTC + DIFF);
  PNEXTTC := CURTC;
  
  -- INSERTAR EL MONTO COMO PROYECTADO EN LA TABLA DE MONTOS
  SELECT 
    ADD_MONTHS(sysdate,(CONTA+1)) INTO NEWFECHA 
  FROM DUAL;
  SELECT 
    EXTRACT(MONTH FROM NEWFECHA),EXTRACT(YEAR FROM NEWFECHA) INTO MES,ANIO
  FROM DUAL;
  -- INSERTAR EN LA TABLA DE MESANIO :'( NOP, PUEDE DAR ERROR DE LLAVE DUPLICADA
  -- INSERT INTO T_MESANIO VALUES (MES,ANIO);
  -- INSERTAR EN LA TABLA DE TIPOS DE CAMBIOS
  INSERT INTO T_TIPOCAMBIOS VALUES (PCODMONEDA1, PCODMONEDA2, PNEXTTC, PCODIDECONO, 2, MES, ANIO);
END;


-- PROYECTA EL TIPO DE CAMBIO PARA N MESES A PARTIR DE LA FECHA ESPECIFICADA
CREATE OR REPLACE PROCEDURE SP_PROYECCIONTCNMESES(
  PNUMMESES IN NUMBER,
  PNUMVALREALES IN NUMBER,
  -- PARA INSERT SOLAMENTE
  PCODMONEDA1 IN NUMBER,
  PCODMONEDA2 IN NUMBER,
  PCODIDECONO IN VARCHAR2
) IS
  CONTA NUMBER(10);
  PMONTO NUMBER(17,2);
  NEWFECHA DATE;
BEGIN
  CONTA := 0;
  PMONTO := 0;
  WHILE (CONTA < PNUMMESES)
  LOOP
    -- INCREMENTA UN MES
    SELECT 
      ADD_MONTHS(sysdate,CONTA) INTO NEWFECHA 
    FROM DUAL;
    -- CALCULA EL TC PARA ESE MES
    SP_PROYECCIONTC1MES(PNUMVALREALES, NEWFECHA, PCODMONEDA1, PCODMONEDA2, PCODIDECONO, PMONTO); 
    CONTA := CONTA + 1;
  END LOOP;
END;



-----------------------------------------------
-- PROYECCIONES DE PRECIO DE PRODUCTO
-----------------------------------------------
-- Retorna un result set con los datos
Create or replace procedure SP_PROYECCIONGENERAR (
    PCODLISTAPRECIO in number,
    PNUMMESES in number,
    PMSGRESPUESTA OUT VARCHAR2
) is
    -- Define variables utilizadas para los calculos
    PORC1 number(3);
    PORC2 number(3);
    PORC3 number(3);
    SUMPORC NUMBER(3);
    SBTPORC NUMBER(17,2);
    CODARTICULO VARCHAR2(20);
    PRCARTICULO NUMBER(17,2);
    MONTOTC NUMBER(17,2);
    SBTPRECIOART NUMBER(17,2);
    TPRECIOART NUMBER(17,2);
    MES NUMBER(2);
    ANIO NUMBER(3);
    CONTA NUMBER(5);
    NEWFECHA DATE;
    -- OBTENER LOS PRECIOS DE LOS ARTICULOS ASOCIADOS A LA LISTA DE PRECIOS 
    -- CURSOR DE PRECIO DE ARTICULOS
    CURSOR CURPRECIOARTIC IS
    SELECT
      ARTIC.CODIGO,
      ARTIC.PRECIOMERCDOLARES
    FROM T_LISTAPRECIOXARTICULOS LPXA INNER JOIN T_ARTICULOS ARTIC ON (LPXA.CODARTICULO = ARTIC.CODIGO)
    WHERE LPXA.CODLISTAPRECIO = PCODLISTAPRECIO;
begin
    -- OBTENER LOS PORCENTAJES DE LA LISTA DE PRECIO
    SELECT
      lpr.gastoAdmin,lpr.gastoOtros,lpr.utilidad INTO PORC1, PORC2, PORC3
    FROM T_ListaPrecios lpr
    WHERE lpr.codigo = PCODLISTAPRECIO;
    PMSGRESPUESTA := '' + 'Obtenido porcentajes\n';

    -- CALCULAR TOTAL DE PORCENTAJES
    SUMPORC := PORC1 + PORC2 + PORC3;
    SBTPORC := SUMPORC / 100;
    SBTPORC := SBTPORC + 1;
    PMSGRESPUESTA := PMSGRESPUESTA + 'Calculado subtotal de porcentajes\n';

    -- PARA CADA ARTICULO EN EL CURSOR, CALCULAR SU PRECIO
    OPEN CURPRECIOARTIC;
    LOOP
      -- EXTRAE DATOS DEL ARTICULO
      FETCH CURPRECIOARTIC INTO CODARTICULO, PRCARTICULO;
      IF (CURPRECIOARTIC%FOUND) THEN
        PMSGRESPUESTA := PMSGRESPUESTA + 'Dato ok en cursor\n';
        -- INICIALIZA CALCULO DE PRECIO PARA LA CANTIDAD DE MESES ESPECIFICADA
        CONTA := 0;
        WHILE (CONTA < PNUMMESES)
        LOOP
          -- INCREMENTA UN MES
          SELECT 
            ADD_MONTHS(sysdate,CONTA) INTO NEWFECHA 
          FROM DUAL;
          -- OBTENER EL MONTO DE TIPO DE CAMBIO PARA ESE MES
          SP_OBTENERTC(NEWFECHA, MONTOTC);
          -- CALCULAR SUBTOTAL DEL PRECIO DEL ARTICULO
          SBTPRECIOART := MONTOTC * PRCARTICULO;
          -- CALCULAR TOTAL DEL PRECIO DEL ARTICULO (APLICA PORCENTAJES)
          TPRECIOART := SBTPRECIOART * (1 + SBTPORC);
          -- EXTRAE EL MES Y EL ANIO DE LA FECHA
          SELECT 
            EXTRACT(MONTH FROM NEWFECHA),EXTRACT(YEAR FROM NEWFECHA) INTO MES,ANIO
          FROM DUAL;
          -- INSERTA UNA FILA DE PROYECCIONES
          INSERT INTO T_PROYECCIONESLISTAPRECIOS VALUES (CODARTICULO, PCODLISTAPRECIO, MES, ANIO, MONTOTC, TPRECIOART);
          -- SIGUE CON EL SIGUIENTE MES DEL MISMO ARTICULO
          CONTA := CONTA + 1;
        END LOOP;
      ELSE
        PMSGRESPUESTA := PMSGRESPUESTA + 'No se encontro datos en cursor\n';
      END IF;
    EXIT WHEN CURPRECIOARTIC %NOTFOUND;
    END LOOP;
End;
